---
# tasks file for ansible-role-win-domain
- name: Windows Feature AD-Domain-Services and Tools
  win_feature:
    name: AD-Domain-Services
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: win_feature

- name: Reboot host and wait for it to restart
  win_reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: win_feature.changed
