---
# tasks file for ansible-role-win-domain
- name: Windows Feature AD-Domain-Services and Tools
  win_feature:
    name: AD-Domain-Services
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: win_feature
  notify: Reboot host and wait for it to restart
